gestion_erp:
    resource: "@GestionERPBundle/Controller/"
    type:     annotation
    prefix:   /

gestion_module:
    resource: "@GestionModuleBundle/Controller/"
    type:     annotation
    prefix:   /

outils:
    resource: "@OutilsBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

# FOS USER BUNDLE
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
