gestion_erp:
    resource: "@GestionERPBundle/Controller/"
    type:     annotation
    prefix:   /

gestion_module:
    resource: "@GestionModuleBundle/Controller/"
    type:     annotation
    prefix:   /

outils:
    resource: "@OutilsBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

# FOS USER BUNDLE
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# GestionERPBundle

# GestionModuleBundle
consultation_module_independant:
    path:     /moduleIndependant
    defaults: { _controller: GestionModuleBundle:Default:moduleIndependant }

creation_module_independant:
    path:     /moduleIndependant/add
    defaults: { _controller: GestionModuleBundle:Default:addModuleIndependant }

modification_module_independant:
    path:     /moduleIndependant/update
    defaults: { _controller: GestionModuleBundle:Default:updateModuleIndependant }

consultation_enchainement_module:
    path:     /enchainementModule
    defaults: { _controller: GestionModuleBundle:Default:enchainementModule }

creation_enchainement_module:
    path:     /enchainementModule/add
    defaults: { _controller: GestionModuleBundle:Default:addEnchainementModule }

# OutilsBundle
historisation:
    path:     /historisation
    defaults: { _controller: OutilsBundle:Default:historisation }

purge:
    path:     /purge
    defaults: { _controller: OutilsBundle:Default:purge }

# PlanningBundle
accueil:
    path:     /
    defaults: { _controller: PlanningBundle:Default:index }

accueil_resultat:
    path:     /indexResultat
    defaults: { _controller: PlanningBundle:Default:indexResultat }

accueil_consultant:
    path:     /consultant
    defaults: { _controller: PlanningBundle:Default:indexConsultant }

accueil_consultant_resultat:
    path:     /consultant/resultat
    defaults: { _controller: PlanningBundle:Default:indexConsultantResultat }

consultation_stagiaire:
    path:     /stagiaire/consultation
    defaults: { _controller: PlanningBundle:Default:consultationStagiaire }

consultation_stagiaire_consultant:
    path:     /stagiaire/consultation/consultant
    defaults: { _controller: PlanningBundle:Default:consultationStagiaireConsultant }

consultation_stagiaire_sanscalendrier:
    path:     /stagiaire/consultation/sanscalendrier
    defaults: { _controller: PlanningBundle:Default:consultationStagiaireSansCalendrier }

creation_planning:
    path:     /planning/add
    defaults: { _controller: PlanningBundle:Default:addPlanning }

modification_planning:
    path:     /planning/update
    defaults: { _controller: PlanningBundle:Default:updatePlanning }

comparaison_planning:
    path:     /planning/comparaison
    defaults: { _controller: PlanningBundle:Default:comparaisonPlanning }

consultation_modele_planning:
    path:     /modele
    defaults: { _controller: PlanningBundle:Default:modele }

creation_modele_planning:
    path:     /modele/add
    defaults: { _controller: PlanningBundle:Default:addModele }

modification_modele_planning:
    path:     /modele/update
    defaults: { _controller: PlanningBundle:Default:updateModele }

# UserBundle
profil:
    path:     /profil
    defaults: { _controller: UserBundle:Default:profil }




