gestion_erp:
    resource: "@GestionERPBundle/Controller/"
    type:     annotation
    prefix:   /

gestion_module:
    resource: "@GestionModuleBundle/Controller/"
    type:     annotation
    prefix:   /

outils:
    resource: "@OutilsBundle/Controller/"
    type:     annotation
    prefix:   /

planning:
    resource: "@PlanningBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

# FOS USER BUNDLE
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


# OutilsBundle
historisation:
    path:     /historisation
    defaults: { _controller: OutilsBundle:Default:historisation }

purge:
    path:     /purge
    defaults: { _controller: OutilsBundle:Default:purge }

# PlanningBundle
accueil:
    path:     /
    defaults: { _controller: PlanningBundle:AdministrateurAccueil:index }

accueil_resultat:
    path:     /indexResultat
    defaults: { _controller: PlanningBundle:Default:indexResultat }

accueil_consultant:
    path:     /consultant
    defaults: { _controller: PlanningBundle:Default:indexConsultant }

accueil_consultant_resultat:
    path:     /consultant/resultat
    defaults: { _controller: PlanningBundle:Default:indexConsultantResultat }

consultation_stagiaire:
    path:     /stagiaire/consultation
    defaults: { _controller: PlanningBundle:Default:consultationStagiaire }

consultation_stagiaire_consultant:
    path:     /stagiaire/consultation/consultant
    defaults: { _controller: PlanningBundle:Default:consultationStagiaireConsultant }

consultation_stagiaire_sanscalendrier:
    path:     /stagiaire/consultation/sanscalendrier
    defaults: { _controller: PlanningBundle:Default:consultationStagiaireSansCalendrier }

creation_planning:
    path:     /planning/add
    defaults: { _controller: PlanningBundle:Default:addPlanning }

modification_planning:
    path:     /planning/update
    defaults: { _controller: PlanningBundle:Default:updatePlanning }

comparaison_planning:
    path:     /planning/comparaison
    defaults: { _controller: PlanningBundle:Default:comparaisonPlanning }

consultation_modele_planning:
    path:     /modele
    defaults: { _controller: PlanningBundle:Default:modele }

creation_modele_planning:
    path:     /modele/add
    defaults: { _controller: PlanningBundle:Default:addModele }

modification_modele_planning:
    path:     /modele/update
    defaults: { _controller: PlanningBundle:Default:updateModele }

# UserBundle
profil:
    path:     /profil
    defaults: { _controller: UserBundle:Default:profil }
